name: UnitTest
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
  pull_request:
    branches: [ development ]
env:
  GET_REPO: export REPO=${GITHUB_REPOSITORY#*/}
  GET_HASH: export HASH=${GITHUB_SHA}

jobs:
  UnitTest:
    name: UnitTest
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Build Source Codes
        run: |
          eval $GET_REPO
          eval $GET_HASH
          echo "=== Build start ==="
          echo 717lumos | sudo -S echo ""         
          sudo useradd -m user && yes password | passwd user
          cd /root/catkin_ws/src/srrg_proslam
          git remote update
          git fetch --all
          git checkout ${BRANCH}
          git pull
          git branch
          cd ~/catkin_ws/src
          catkin build --make-args tests -- srrg_proslam
          echo "=== Build finished ==="

      - name: Test - Run Unit Test
        run: |
          echo "=== Unit Test start ==="
          cd /root/catkin_ws/devel/lib/srrg_proslam
          ./test_app
          echo "=== Unit Test finished ==="

      - name: If Fail - Clean up Docker image if test fails
        if: failure()
        run: |
          echo "=== Clean up start ==="
          echo 717lumos | sudo -S echo ""
          sudo docker rmi -f $(sudo docker images -f "dangling=true" -q)
          sudo docker images
          echo "=== Clean up finished ==="
